version: 2

aliases:
  # Workflow filters
  - &filter-only-release
    branches:
      ignore: /.*/
    tags:
      only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
  - &filter-not-release-or-master
    tags:
      ignore: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
    branches:
      ignore: master
  - &filter-only-master
    branches:
      only: master

defaults: &defaults
  working_directory: ~/kentik-connect-app
  docker:
    - image: circleci/node:14-stretch-browsers
  environment:
    PLUGIN_NAME: kentik-connect-app

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Build
          command: |
            yarn install
            npm run build
            sudo apt-get install jq
            VERSION=`cat dist/plugin.json|jq '.info.version'| sed s/\"//g`
            # create zip file
            cd ~
            echo "Creating ZIP"
            cp -r ${PLUGIN_NAME}/dist/ /tmp/${PLUGIN_NAME}
            cd /tmp
            zip \
              -r ${PLUGIN_NAME}-${VERSION}.zip \
              ${PLUGIN_NAME}
            # create tar file
            echo "Creating TAR"
            tar \
              -zcvf ${PLUGIN_NAME}-${VERSION}.tar.gz \
              ${PLUGIN_NAME}
            # create artifacts
            mkdir -p ~/${PLUGIN_NAME}/artifacts
            mv ${PLUGIN_NAME}-${VERSION}.zip ~/${PLUGIN_NAME}/artifacts/
            mv ${PLUGIN_NAME}-${VERSION}.tar.gz ~/${PLUGIN_NAME}/artifacts/
          no_output_timeout: 5m
      - save_cache:
          name: Save NPM Package Cache
          key: v1-npm-deps-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/npm
      - persist_to_workspace:
          root: .
          paths:
            - artifacts
            - dist
      - store_artifacts:
          path: artifacts
      - store_artifacts:
          path: dist

  tslint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
      - run:
          name: TSLint
          command: |
            yarn install
            npm run tslint

  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "yarn.lock" }}
      - run:
          name: Test
          command: |
            yarn install
            sudo npm install -g jest
            npm test

workflows:
  version: 2
  build-master:
    jobs:
      - tslint:
          filters: *filter-only-master
      - test:
          requires:
            - tslint
          filters: *filter-only-master
      - build:
          requires:
            - test
          filters: *filter-only-master

  build-branches-and-prs:
    jobs:
      - tslint:
          filters: *filter-not-release-or-master
      - test:
          requires:
            - tslint
          filters: *filter-not-release-or-master
      - build:
          requires:
            - test
          filters: *filter-not-release-or-master
